[2019-10-02 22:05:50,229] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Stage_dim_data_files 2019-10-03T03:05:20.608191+00:00 [queued]>
[2019-10-02 22:05:50,267] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Stage_dim_data_files 2019-10-03T03:05:20.608191+00:00 [queued]>
[2019-10-02 22:05:50,267] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-10-02 22:05:50,268] {taskinstance.py:839} INFO - Starting attempt 1 of 4
[2019-10-02 22:05:50,268] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-10-02 22:05:50,281] {taskinstance.py:859} INFO - Executing <Task(LoadLocalFilesToS3Operator): Stage_dim_data_files> on 2019-10-03T03:05:20.608191+00:00
[2019-10-02 22:05:50,281] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_project_dag', 'Stage_dim_data_files', '2019-10-03T03:05:20.608191+00:00', '--job_id', '254', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/project_dag.py', '--cfg_path', '/var/folders/dr/9yvjlnm11xv25k2gknf2n3z00000gn/T/tmpcc92liu6']
[2019-10-02 22:05:51,164] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files /usr/local/lib/python3.7/site-packages/airflow/configuration.py:627: DeprecationWarning: You have two airflow.cfg files: /Users/victorialemay/airflow/airflow.cfg and /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg, and you should remove the other file
[2019-10-02 22:05:51,165] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   category=DeprecationWarning,
[2019-10-02 22:05:51,302] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files [2019-10-02 22:05:51,302] {settings.py:213} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=62824
[2019-10-02 22:05:51,619] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files [2019-10-02 22:05:51,619] {__init__.py:51} INFO - Using executor LocalExecutor
[2019-10-02 22:05:52,408] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files [2019-10-02 22:05:52,408] {dagbag.py:90} INFO - Filling up the DagBag from /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/dags/project_dag.py
[2019-10-02 22:05:52,488] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files [2019-10-02 22:05:52,488] {cli.py:516} INFO - Running <TaskInstance: capstone_project_dag.Stage_dim_data_files 2019-10-03T03:05:20.608191+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2019-10-02 22:05:53,023] {logging_mixin.py:95} INFO - [[34m2019-10-02 22:05:53,019[0m] {[34mS3_hook.py:[0m59} INFO[0m - Not Found[0m
[2019-10-02 22:05:53,674] {taskinstance.py:1051} ERROR - An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/load_files_to_s3.py", line 47, in execute
    s3.create_bucket(self.s3_bucket, region_name='us-west-2')
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/S3_hook.py", line 89, in create_bucket
    'LocationConstraint': region_name
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
[2019-10-02 22:05:53,680] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-10-02 22:05:53,737] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files Traceback (most recent call last):
[2019-10-02 22:05:53,737] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/bin/airflow", line 32, in <module>
[2019-10-02 22:05:53,737] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     args.func(args)
[2019-10-02 22:05:53,737] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-02 22:05:53,737] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     return f(*args, **kwargs)
[2019-10-02 22:05:53,737] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-10-02 22:05:53,737] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     _run(args, dag, ti)
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     pool=args.pool,
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     return func(*args, **kwargs)
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     result = task_copy.execute(context=context)
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/load_files_to_s3.py", line 47, in execute
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     s3.create_bucket(self.s3_bucket, region_name='us-west-2')
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/S3_hook.py", line 89, in create_bucket
[2019-10-02 22:05:53,738] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     'LocationConstraint': region_name
[2019-10-02 22:05:53,739] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
[2019-10-02 22:05:53,739] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     return self._make_api_call(operation_name, kwargs)
[2019-10-02 22:05:53,739] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
[2019-10-02 22:05:53,739] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files     raise error_class(parsed_response, operation_name)
[2019-10-02 22:05:53,739] {base_task_runner.py:115} INFO - Job 254: Subtask Stage_dim_data_files botocore.exceptions.ClientError: An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
[2019-10-02 22:05:55,213] {logging_mixin.py:95} INFO - [[34m2019-10-02 22:05:55,212[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
