[2019-10-02 17:45:47,738] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Stage_dim_data_files 2019-10-02T22:45:31.885320+00:00 [queued]>
[2019-10-02 17:45:47,747] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Stage_dim_data_files 2019-10-02T22:45:31.885320+00:00 [queued]>
[2019-10-02 17:45:47,747] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-10-02 17:45:47,747] {taskinstance.py:839} INFO - Starting attempt 1 of 4
[2019-10-02 17:45:47,747] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-10-02 17:45:47,767] {taskinstance.py:859} INFO - Executing <Task(LoadLocalFilesToS3Operator): Stage_dim_data_files> on 2019-10-02T22:45:31.885320+00:00
[2019-10-02 17:45:47,767] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_project_dag', 'Stage_dim_data_files', '2019-10-02T22:45:31.885320+00:00', '--job_id', '131', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/project_dag.py', '--cfg_path', '/var/folders/dr/9yvjlnm11xv25k2gknf2n3z00000gn/T/tmp5_zq1bat']
[2019-10-02 17:45:48,250] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files /usr/local/lib/python3.7/site-packages/airflow/configuration.py:627: DeprecationWarning: You have two airflow.cfg files: /Users/victorialemay/airflow/airflow.cfg and /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg, and you should remove the other file
[2019-10-02 17:45:48,251] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   category=DeprecationWarning,
[2019-10-02 17:45:48,347] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files [2019-10-02 17:45:48,346] {settings.py:213} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=17084
[2019-10-02 17:45:48,591] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files [2019-10-02 17:45:48,590] {__init__.py:51} INFO - Using executor LocalExecutor
[2019-10-02 17:45:48,948] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files [2019-10-02 17:45:48,948] {dagbag.py:90} INFO - Filling up the DagBag from /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/dags/project_dag.py
[2019-10-02 17:45:48,992] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files [2019-10-02 17:45:48,991] {cli.py:516} INFO - Running <TaskInstance: capstone_project_dag.Stage_dim_data_files 2019-10-02T22:45:31.885320+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2019-10-02 17:45:49,055] {load_files_to_s3.py:29} INFO - Checking /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/dim_table_data directory for files
[2019-10-02 17:45:49,056] {load_files_to_s3.py:33} INFO - Found files:
[2019-10-02 17:45:49,056] {load_files_to_s3.py:35} INFO -   /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/dim_table_data/visa_types.json
[2019-10-02 17:45:49,056] {load_files_to_s3.py:37} INFO -     visa_types.json
[2019-10-02 17:45:50,235] {taskinstance.py:1051} ERROR - Unable to locate credentials
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/load_files_to_s3.py", line 38, in execute
    s3.load_file(file, key, self.s3_bucket)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/S3_hook.py", line 342, in load_file
    if not replace and self.check_for_key(key, bucket_name):
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/S3_hook.py", line 198, in check_for_key
    self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 157, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 425, in add_auth
    super(S3SigV4Auth, self).add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2019-10-02 17:45:50,245] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-10-02 17:45:50,276] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files Traceback (most recent call last):
[2019-10-02 17:45:50,276] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/bin/airflow", line 32, in <module>
[2019-10-02 17:45:50,276] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     args.func(args)
[2019-10-02 17:45:50,276] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-02 17:45:50,276] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     return f(*args, **kwargs)
[2019-10-02 17:45:50,276] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-10-02 17:45:50,276] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     _run(args, dag, ti)
[2019-10-02 17:45:50,276] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     pool=args.pool,
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     return func(*args, **kwargs)
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     result = task_copy.execute(context=context)
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/load_files_to_s3.py", line 38, in execute
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     s3.load_file(file, key, self.s3_bucket)
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/S3_hook.py", line 342, in load_file
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     if not replace and self.check_for_key(key, bucket_name):
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/S3_hook.py", line 198, in check_for_key
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     self.get_conn().head_object(Bucket=bucket_name, Key=key)
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     return self._make_api_call(operation_name, kwargs)
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 648, in _make_api_call
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     operation_model, request_dict, request_context)
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 667, in _make_request
[2019-10-02 17:45:50,277] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     return self._endpoint.make_request(operation_model, request_dict)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     return self._send_request(request_dict, operation_model)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     request = self.create_request(request_dict, operation_model)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     operation_name=operation_model.name)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     return self._emitter.emit(aliased_event_name, **kwargs)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     return self._emit(event_name, kwargs)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     response = handler(**kwargs)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     return self.sign(operation_name, request)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 157, in sign
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     auth.add_auth(request)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 425, in add_auth
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     super(S3SigV4Auth, self).add_auth(request)
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files   File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 357, in add_auth
[2019-10-02 17:45:50,278] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files     raise NoCredentialsError
[2019-10-02 17:45:50,279] {base_task_runner.py:115} INFO - Job 131: Subtask Stage_dim_data_files botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2019-10-02 17:45:52,726] {logging_mixin.py:95} INFO - [[34m2019-10-02 17:45:52,725[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
