[2019-10-04 12:23:24,386] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Load_visa_types_dim_table 2019-10-04T17:11:49.652690+00:00 [queued]>
[2019-10-04 12:23:24,409] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Load_visa_types_dim_table 2019-10-04T17:11:49.652690+00:00 [queued]>
[2019-10-04 12:23:24,409] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-10-04 12:23:24,409] {taskinstance.py:839} INFO - Starting attempt 3 of 4
[2019-10-04 12:23:24,409] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-10-04 12:23:24,418] {taskinstance.py:859} INFO - Executing <Task(LoadDimFileData): Load_visa_types_dim_table> on 2019-10-04T17:11:49.652690+00:00
[2019-10-04 12:23:24,418] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_project_dag', 'Load_visa_types_dim_table', '2019-10-04T17:11:49.652690+00:00', '--job_id', '516', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/project_dag.py', '--cfg_path', '/var/folders/dr/9yvjlnm11xv25k2gknf2n3z00000gn/T/tmp8os3abw2']
[2019-10-04 12:23:24,913] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table /usr/local/lib/python3.7/site-packages/airflow/configuration.py:627: DeprecationWarning: You have two airflow.cfg files: /Users/victorialemay/airflow/airflow.cfg and /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg, and you should remove the other file
[2019-10-04 12:23:24,914] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   category=DeprecationWarning,
[2019-10-04 12:23:25,010] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table [2019-10-04 12:23:25,010] {settings.py:213} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=70019
[2019-10-04 12:23:25,264] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table [2019-10-04 12:23:25,263] {__init__.py:51} INFO - Using executor LocalExecutor
[2019-10-04 12:23:25,627] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table [2019-10-04 12:23:25,627] {dagbag.py:90} INFO - Filling up the DagBag from /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/dags/project_dag.py
[2019-10-04 12:23:25,673] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table [2019-10-04 12:23:25,673] {cli.py:516} INFO - Running <TaskInstance: capstone_project_dag.Load_visa_types_dim_table 2019-10-04T17:11:49.652690+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2019-10-04 12:23:25,710] {load_dim_file_data.py:35} INFO - Using data file visa_types.json from S3 bucket project-capstone
[2019-10-04 12:23:25,750] {logging_mixin.py:95} INFO - [[34m2019-10-04 12:23:25,750[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-04 12:23:26,557] {taskinstance.py:1051} ERROR - relation "visa_types" does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/load_dim_file_data.py", line 42, in execute
    records = redshift.get_records("SELECT COUNT(*) FROM {}".format(self.table))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 117, in get_records
    cur.execute(sql)
psycopg2.errors.UndefinedTable: relation "visa_types" does not exist

[2019-10-04 12:23:26,563] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table Traceback (most recent call last):
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   File "/usr/local/bin/airflow", line 32, in <module>
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table     args.func(args)
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table     return f(*args, **kwargs)
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table     _run(args, dag, ti)
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table     pool=args.pool,
[2019-10-04 12:23:26,588] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table     return func(*args, **kwargs)
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table     result = task_copy.execute(context=context)
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/load_dim_file_data.py", line 42, in execute
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table     records = redshift.get_records("SELECT COUNT(*) FROM {}".format(self.table))
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 117, in get_records
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table     cur.execute(sql)
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table psycopg2.errors.UndefinedTable: relation "visa_types" does not exist
[2019-10-04 12:23:26,589] {base_task_runner.py:115} INFO - Job 516: Subtask Load_visa_types_dim_table 
[2019-10-04 12:23:29,372] {logging_mixin.py:95} INFO - [[34m2019-10-04 12:23:29,371[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
